# _config.yml
#
# for official documentation: https://jekyllrb.com/docs/configuration/
# based on theme: https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml
remote_theme: daattali/beautiful-jekyll

# basic
title: Smash64 Online
#description
author: CEnnis91

# navigation bar
navbar-links:
  Getting Started: http://smash64.online
  Discords:
    - North America: "https://discord.gg/ssb64"
    - Europe: "https://discord.gg/YvbVHD7"
    - Australia: "https://discord.gg/ssb64australia"
    - Latin America: "https://discord.gg/rdVGwUv"
  Download: "https://github.com/smash64-dev/project64k-legacy/releases/latest/download/project64k-legacy.zip"

# logo
avatar: "/assets/img/kirbox.png"
round-avatar: false
#title-img:

# general
#share-links-active:
url-pretty: "Smash64.Online"
link-tags: true
excerpt_length: 50

# colors / images
colors:
  base:
    primary: "#675ff5"
    background: "#222831"
    navbar-text: "#eeeeee"
    footer-text: "#eeeeee"
    footer-social: "#222831"
    footer-icons: "#eeeeee"
    main-text: "#eeeeee"
    main-weak: "#cccccc"
    link: "#675ff5"
    select: "#ffffff"
  border:
    dark: "#000000"
    light: "#dddddd"
    middle: "#7f7f7f"
  box:
    dark: "#000000"
    error: "#dc3545"
    light: "#ffffff"
    note: "#007bff"
    success: "#28a745"
    warning: "#ffc107"

#navbar-img:
#footer-img:
#page-img:

# web statistics
#gtag: 
google_analytics: 'UA-171766730-1'
#gtm:
#matomo:

# comments
#disqus:
#fb_comment_id:
#utterances:
#staticman:

# misc
date_format: "%a, %B %-d, %Y"
#fb_app_id:
title-separator: "-"

# compress
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []

# jekyll
highlighter: rouge
markdown: kramdown
paginate: 5
permalink: /:year-:month-:day-:title/
timezone: "America/New_York"

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      show-avatar: true
      social-share: false
      readtime: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor/
